/*
SHOP ARRAYS
0 : Display Text
1 : Item Type
2 : Item ID
3 : Cost Multiplier
*/

private _mult = shopPriceMult;


private _r = [["rhs_weap_m4a1_carryhandle","","","",["rhs_mag_30Rnd_556x45_M855A1_Stanag",30],[],""],[],[],["rhs_uniform_cu_ocp_10th",[]],["rhsusf_iotv_ucp_Rifleman",[["rhs_mag_30Rnd_556x45_M855A1_Stanag",5,30]]],[],"rhsusf_ach_helmet_ucp","",[],["ItemMap","ItemGPS","","ItemCompass","ItemWatch",""]];
private _breacher = [["rhs_weap_M590_8RD","","","",["rhsusf_5Rnd_00Buck",5],[],""],[],[],["rhs_uniform_cu_ocp_10th",[]],["rhsusf_iotv_ucp_Rifleman",[["rhsusf_5Rnd_00Buck",5,5],["rhsusf_5Rnd_Slug",5,5]]],["rhsusf_falconii_breach",[["ACE_Clacker",1],["rhsusf_m112_mag",2,1],["ClaymoreDirectionalMine_Remote_Mag",1,1]]],"rhsusf_ach_helmet_ucp","",[],["ItemMap","ItemGPS","","ItemCompass","ItemWatch",""]];
private _medic =[["rhs_weap_m4a1_carryhandle","","","",["rhs_mag_30Rnd_556x45_Mk318_Stanag",30],[],""],[],[],["rhs_uniform_cu_ocp_10th",[]],["rhsusf_iotv_ucp_Medic",[["rhs_mag_30Rnd_556x45_M855A1_Stanag",5,30]]],["rhsusf_falconii_sarc",[["ACE_tourniquet",5],["ACE_splint",5],["ACE_EarPlugs",5],["ACE_epinephrine",5],["ACE_morphine",5],["ACE_surgicalKit",1],["ACE_bloodIV",2],["ACE_bloodIV_500",3],["ACE_bloodIV_250",4],["ACE_fieldDressing",25],["kat_AED",1],["Chemlight_red",1,1]]],"rhsusf_ach_helmet_ucp_alt","",[],["ItemMap","ItemGPS","","ItemCompass","ItemWatch",""]];
private _uav = [["rhs_weap_m4_carryhandle","","","",["rhs_mag_30Rnd_556x45_M855A1_Stanag",30],[],""],[],[],["rhs_uniform_cu_ocp_10th",[]],["rhsusf_iotv_ucp_Rifleman",[["rhs_mag_30Rnd_556x45_M855A1_Stanag",5,30]]],["B_UAV_01_backpack_F",[]],"rhsusf_ach_helmet_ucp","",[],["ItemMap","B_UavTerminal","","ItemCompass","ItemWatch",""]];
private _marksman =[["rhs_weap_m14ebrri_leu","","","rhsusf_acc_ACOG3",["rhsusf_20Rnd_762x51_m118_special_Mag",20],[],"rhsusf_acc_harris_bipod"],[],[],["rhs_uniform_cu_ocp_10th",[]],["rhsusf_iotv_ucp_Rifleman",[["rhsusf_20Rnd_762x51_m118_special_Mag",3,20]]],[],"rhsusf_ach_helmet_ucp","",[],["ItemMap","ItemGPS","","ItemCompass","ItemWatch",""]];
private _at = [["rhs_weap_m4_carryhandle","","","",["rhs_mag_30Rnd_556x45_M855A1_Stanag",30],[],""],["rhs_weap_M136","","","",["rhs_m136_mag",1],[],""],[],["rhs_uniform_cu_ocp_10th",[]],["rhsusf_iotv_ucp_Rifleman",[["rhs_mag_30Rnd_556x45_M855A1_Stanag",5,30]]],[],"rhsusf_ach_helmet_ucp","",[],["ItemMap","ItemGPS","","ItemCompass","ItemWatch",""]];
private _ar = [["rhs_weap_m249_light_S","","","",["rhsusf_100Rnd_556x45_mixed_soft_pouch_coyote",100],[],"rhsusf_acc_saw_lw_bipod"],[],[],["rhs_uniform_cu_ocp_10th",[]],["rhsusf_iotv_ucp_SAW",[["rhsusf_100Rnd_556x45_mixed_soft_pouch_coyote",3,100]]],[],"rhsusf_ach_helmet_ucp","",[],["ItemMap","ItemGPS","","ItemCompass","ItemWatch",""]];
private _gr = [["rhs_weap_m4a1_carryhandle_m203","","","",["rhs_mag_30Rnd_556x45_M855A1_Stanag",30],["rhs_mag_M433_HEDP",1],""],[],[],["rhs_uniform_cu_ocp_10th",[]],["rhsusf_iotv_ucp_Grenadier",[["rhs_mag_30Rnd_556x45_M855A1_Stanag",5,30]]],["rhsusf_assault_eagleaiii_ucp",[["rhs_mag_M433_HEDP",3,1],["rhs_mag_m4009",3,1],["UGL_FlareWhite_F",3,1],["1Rnd_Smoke_Grenade_shell",3,1]]],"rhsusf_ach_helmet_headset_ucp_alt","",[],["ItemMap","ItemGPS","","ItemCompass","ItemWatch",""]];
private _spec = [["rhs_weap_hk416d10_LMT_d","rhsusf_acc_nt4_tan","rhsusf_acc_anpeq15_wmx_light","rhsusf_acc_eotech_552_d",["rhs_mag_30Rnd_556x45_Mk318_PMAG_Tan",30],[],"rhsusf_acc_kac_grip"],[],["rhsusf_weap_m9","","","",[],[],""],["rhs_uniform_g3_mc",[]],["rhsusf_mbav_rifleman",[["rhs_mag_30Rnd_556x45_Mk318_PMAG_Tan",5,30]]],[],"rhsusf_opscore_mc_cover_pelt_cam","",[],["ItemMap","ItemGPS","","ItemCompass","ItemWatch",""]];
private _eod = [["rhs_weap_m4a1_carryhandle","","","",["rhs_mag_30Rnd_556x45_M855A1_Stanag",30],[],""],[],[],["rhs_uniform_cu_ocp_10th",[]],["rhsusf_iotv_ucp_Repair",[["rhs_mag_30Rnd_556x45_M855A1_Stanag",5,30]]],["rhsusf_assault_eagleaiii_ucp",[["ACE_DefusalKit",1],["ToolKit",1],["rhsusf_m112_mag",1,1]]],"rhsusf_ach_helmet_ESS_ucp","",[],["ItemMap","ItemGPS","","ItemCompass","ItemWatch",""]];
private _translator = [["UK3CB_M16A2","","","",["rhs_mag_30Rnd_556x45_M855A1_Stanag",30],[],""],[],[],["UK3CB_ANA_B_U_CombatUniform_01_SPEC4CE",[]],["UK3CB_ANA_B_V_RFL_Vest_WDL_01",[["rhs_mag_30Rnd_556x45_M855A1_Stanag",5,30]]],[],"UK3CB_ANA_B_H_6b27m_SPEC4CE","",[],["ItemMap","ItemGPS","","ItemCompass","ItemWatch",""]];

bluforShopList = [["Rifleman", "loadout", _r, 3], ["Medic", "loadout", _medic, 5, "player setUnitTrait ['Medic', true];"], ["Breacher", "loadout", _breacher, 5], ["UAV Operator", "loadout", _uav, 6.5], ["Marksman", "loadout", _marksman, 7], ["Rifleman (AT)", "loadout", _at, 4], ["Autorifleman", "loadout", _ar, 6], ["Grenadier", "loadout", _gr, 6], ["EOD Specialist", "loadout", _eod, 5.5, "player addItemToBackpack 'ACE_VMM3'; player setUnitTrait ['explosiveSpecialist ', true]"], ["Spec-Op", "loadout", _spec, 8], ["Translator", "loadout", _translator, 5, "[player, (selectRandom ['PersianHead_A3_01', 'PersianHead_A3_02', 'PersianHead_A3_03'])] remoteExec ['setFace', 0, true]; ['en', 'pa'] call acre_api_fnc_babelSetSpokenLanguages"], ["M67 Grenade", "item", ["rhs_mag_m67"], 1], ["White Smoke Grenade", "item", ["rhs_mag_an_m8hc"], 0.5], ["m84 Stun Grenade", "item", ["ACE_M84"], 0.6], ["AN-M14 Incendiary Grenade", "item", ["ACE_M14"], 1], ["FAK", "item", ["FirstAidKit"], 0.5], ["M552 CCO Sights", "item", ["rhsusf_acc_eotech_552", true], 0.5], ["WMX Flashlight", "item", ["rhsusf_acc_wmx_bk"], 0.5], ["AN/PVS-15 NVGs", "item", ["rhsusf_ANPVS_15", true], 1.5]];

civShopList = [["Rocks", "item", ["HandGrenade_stone",false, 3], 0],["Mosin", "weapon", ["rhs_weap_m38"], 5], ["Lee Enfield", "weapon", ["UK3CB_Enfield"], 5.5], ["M1 Garand", "weapon", ["rhs_weap_m1garand_sa43"], 6], ["AK-47", "weapon", ["uk3cb_ak47"], 6.5], ["AKM", "weapon", ["rhs_weap_akm"], 7], ["SKS", "weapon", ["uk3cb_sks_01_sling"], 7], ["Browning HP", "weapon", ["UK3CB_BHP"], 2], ["Flashlight", "weapon", ["ACE_Flashlight_Maglite_ML300L", 0], 1], ["Binoculars", "weapon", ["binocular", 0], 1.5], ["Hip Pouch", "equipment", ["UK3CB_V_Pouch", "vest"], 1], ["Knapsack Backpack", "equipment", ["UK3CB_UN_B_B_ASS","backpack"], 2], ["Messenger Backpack", "equipment", ["B_Messenger_Gray_F", "backpack"], 1.5], ["Medical Backpack + Supplies", "misc", "", 5, "'UK3CB_B_Alice_Med_K' execVM 'scripts\makePlayerMedic.sqf'"], ["Radio", "item", [civRadio], 1.5], ["Perk: Translator", "misc", "", 5.5, "['en', 'pa'] call acre_api_fnc_babelSetSpokenLanguages"]];

opforShopList = [["Mosin", "weapon", ["rhs_weap_m38"], 0.5], ["Lee Enfield", "weapon", ["UK3CB_Enfield"], 1], ["M1 Garand", "weapon", ["rhs_weap_m1garand_sa43"], 1.5], ["AK-47", "weapon", ["uk3cb_ak47"], 2], ["AKM", "weapon", ["rhs_weap_akm"], 2.5], ["SKS", "weapon", ["uk3cb_sks_01_sling"], 2.5], ["Browning HP", "weapon", ["UK3CB_BHP"], 0.5],["PKM", "weapon", ["rhs_weap_pkm", 1], 6.5], ["RPK", "weapon", ["UK3CB_RPK", 1, "rhs_75Rnd_762x39mm"], 6], ["PPsh41", "weapon", ["uk3cb_ppsh41", 2], 4], ["MG3", "weapon", ["UK3CB_MG3", 2], 7], ["SVD", "weapon", ["UK3CB_SVD_OLD"], 6], ["VSS", "weapon", ["rhs_weap_vss"], 7], ["AKM (GP-25)", "weapon", ["rhs_weap_akm_gp25", 3, "rhs_30Rnd_762x39mm"], 4.5, "player addWeaponItem ['rhs_weap_akm_gp25', 'rhs_VOG25', true]"], ["Škorpion", "weapon", ["rhs_weap_savz61"], 1.5], ["RPG-26", "weapon", ["rhs_weap_rpg26", 0], 2.5], ["RPG-7V2", "weapon", ["rhs_weap_rpg7", 2, "rhs_rpg7_PG7VL_mag"], 4.5], ["VOG25 Grenade Shell", "item", ["rhs_VOG25"], 0.5], ["PSO-1M2 Scope", "item", ["rhs_acc_pso1m2"], 1], ["RGD-5 Grenade", "item", ["rhs_mag_rgd5"],0.5], ["RDG-2 Smoke Grenade (White)", "item", ["rhs_mag_rdg2_white"], 0.25], ["Heavy Ballistic Vest", "equipment", ["UK3CB_TKA_B_V_GA_LITE_TAN", "vest"], 2.5], ["Light Ballistic Vest", "equipment", ["UK3CB_TKA_B_V_TacVest_Tan", "vest"], 1], ["Face Mask", "equipment", ["UK3CB_G_Face_Wrap_01", "goggles"], 0.1], ["Carryall Backpack", "equipment", ["B_Carryall_khk", "backpack"], 1.5], ["Large IED", "item", ["IEDUrbanBig_Remote_Mag"], 2], ["Small IED", "item", ["IEDLandSmall_Remote_Mag"], 1.5], ["Cellphone Detonator", "item", ["ACE_Cellphone"], 0.5], ["Dead Men's Switch", "item", ["ACE_DeadManSwitch"], 1]];

{ { _x set [3, ( [(_x select 3), _mult] call occupation_fnc_getPrice)] } forEach _x } forEach [bluforShopList, civShopList, opforShopList];

